name: "Registry Login"
description: "Reusable action for logging in to container registries using workflow vars and secrets"
runs:
  using: "composite"
  steps:
    - run: |
        case "${{ vars.REGISTRY_PROVIDER }}" in
          "gcp")
            echo "Using Google Container Registry"
            echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcloud-key.json
            gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
            gcloud auth configure-docker ${{ secrets.REGISTRY_NAME }}
            REGISTRY_URL=$(echo "${{ secrets.REGISTRY_URL }}" | tr '[:upper:]' '[:lower:]')
            ;;
          "azure" | "dockerhub")
            echo "Logging in to Container Registry"
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_NAME }} \
              --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
            REGISTRY_URL=$(echo "${{ secrets.REGISTRY_URL }}" | tr '[:upper:]' '[:lower:]')
            ;;
          *)
            echo "Using GitHub Container Registry (GHCR)"
            REPO_NAME_LOWERCASE=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            REGISTRY_URL="ghcr.io/$REPO_NAME_LOWERCASE"
            ;;
        esac
        echo "REGISTRY_URL=${REGISTRY_URL}" >> $GITHUB_ENV
      shell: bash